substitutions:
  log_level: "INFO"
  indicator_brightness_when_offline_percent: "100"
  default_indicator_on_with_dimmer: "false"
  default_change_indicator_brightness_with_dimmer: "false"
  default_indicator_brightness_when_on: "100"
  default_indicator_brightness_when_off: "60"

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  project:
    name: "elegrp.DTR10-DTR30"
    version: "1.5"
  on_boot:
    then:
      - delay: 3s
      # Set brightness to highest setting
      - number.to_max: dimmer_brightness_control

bk72xx:
  board: cb2s

globals:
  - id: indicator_on_with_dimmer_state
    type: bool
    restore_value: true
    initial_value: ${default_indicator_on_with_dimmer}
  - id: change_indicator_brightness_with_dimmer_state
    type: bool
    restore_value: true
    initial_value: ${default_change_indicator_brightness_with_dimmer}

# Enable Home Assistant API
api:
  id: id_esphome_api
  encryption:
    key: ${api_key}
  # If device disconnected from API for 10 minutes, turn off the indicator LEDs.
  on_client_disconnected:
    if:
      condition:
        for:
          time: 10min
          condition:
            not:
              api.connected:
      then:
        - number.set:
            id: indicator_brightness
            value: ${indicator_brightness_when_offline_percent}

ota:
  - platform: esphome
    id: id_esphome_ota
    password: ${ota_password}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Power save on LibreTiny is boolean so HIGH or LIGHT have the same effect
  power_save_mode: HIGH

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${hotspot_name}
    password: ${hotspot_password}

captive_portal:
  id: id_captive_portal

# Enable logging
logger:
  level: ${log_level}
  baud_rate: 0 # Disable log to uart because using Uart for TuyaMCU

web_server:
  port: 80
  version: 3
  id: id_web_server
  ota: false

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

sensor:
  - platform: wifi_signal
    name: "WiFi RSSI"
    update_interval: 60s
    entity_category: diagnostic
    web_server:
      sorting_weight: 202
  - platform: internal_temperature
    name: "CPU Temperature"
    id: id_sensor_internal_temperature
    entity_category: diagnostic
    web_server:
      sorting_weight: 210

text_sensor:
  - platform: tuya
    name: "TuyaMCU Version"
    sensor_datapoint: 113
    entity_category: diagnostic
    web_server:
      sorting_weight: 100
  - platform: tuya
    name: "Hardware Version"
    sensor_datapoint: 109
    entity_category: diagnostic
    web_server:
      sorting_weight: 101
  - platform: wifi_info
    ssid:
      name: "WiFi SSID"
      entity_category: diagnostic
      web_server:
        sorting_weight: 201
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
      web_server:
        sorting_weight: 203
    mac_address:
      name: "MAC Address"
      entity_category: diagnostic
      web_server:
        sorting_weight: 204
  - platform: template
    name: "Wifi Channel"
    entity_category: diagnostic
    web_server:
        sorting_weight: 205
    lambda: |-
      std::string out;
      char buffer[10];
      snprintf(buffer, 10, "%u", WiFi.channel());
      out.append(buffer);
      return out;
    update_interval: 60s
  - platform: uptime
    name: "Uptime"

button:
  - platform: restart
    name: "Restart Device"
    id: id_button_device_restart
    web_server:
      sorting_weight: 300

tuya:
  # DPIDs processed from schema model: 000004ngxw
  id: id_tuya_device

switch:
  #- platform: tuya
  #  switch_datapoint: 110
  #  name: Countdown Action
  - platform: tuya
    switch_datapoint: 114
    name: "Set Brightness Min"
    id: id_switch_set_brightness_min
    entity_category: config
    web_server:
      sorting_weight: 11
  - platform: template
    name: "Indicator On With Dimmer"
    id: indicator_on_with_dimmer_toggle
    # web_server:
    #     sorting_weight: 103
    entity_category: config
    disabled_by_default: true
    restore_mode: DISABLED
    lambda: "return id(indicator_on_with_dimmer_state) == true;"
    turn_on_action:
      - globals.set:
          id: indicator_on_with_dimmer_state
          value: "true"
    turn_off_action:
      - globals.set:
          id: indicator_on_with_dimmer_state
          value: "false"
      - globals.set:
          id: change_indicator_brightness_with_dimmer_state
          value: "false"
  - platform: template
    name: "Indicator Changes Brightness With Dimmer"
    id: change_indicator_brightness_with_dimmer_toggle
    # web_server:
    #     sorting_weight: 103
    entity_category: config
    disabled_by_default: true
    restore_mode: DISABLED
    lambda: "return id(change_indicator_brightness_with_dimmer_state) == true;"
    turn_on_action:
      - globals.set:
          id: change_indicator_brightness_with_dimmer_state
          value: "true"
    turn_off_action:
      - globals.set:
          id: change_indicator_brightness_with_dimmer_state
          value: "false"


number:
  # Non-Tuya Configuration Numbers
  - platform: template
    name: "Indicator Brightness When On"
    id: indicator_brightness_when_on
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    entity_category: config
    disabled_by_default: true
    restore_value: true
    initial_value: ${default_indicator_brightness_when_on}
  - platform: template
    name: "Indicator Brightness When Off"
    id: indicator_brightness_when_off
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    entity_category: config
    disabled_by_default: true
    restore_value: true
    initial_value: ${default_indicator_brightness_when_off}
  # Allows for setting brightness value without turning the light ON
  - platform: tuya
    number_datapoint: 2
    name: "Dimmer Brightness"
    id: dimmer_brightness_control
    min_value: 1
    max_value: 100
    step: 1
    # TuyaMCU scale is 10 to 1000
    multiply: 10
    web_server:
      sorting_weight: 0
  - platform: tuya
    number_datapoint: 108
    name: "Longpress Brightness"
    id: id_number_longpress_brightness
    min_value: 10
    max_value: 1000
    step: 1
    entity_category: config
    web_server:
      sorting_weight: 1
  - platform: tuya
    number_datapoint: 101
    name: "Indicator Brightness"
    id: indicator_brightness
    min_value: 0
    max_value: 100
    step: 1
    entity_category: config
    web_server:
      sorting_weight: 2
  - platform: tuya
    number_datapoint: 5
    name: "Brightness Max"
    id: id_number_brightness_max
    min_value: 550
    max_value: 1000
    step: 1
    entity_category: config
    web_server:
      sorting_weight: 10
  # User must activate "Set Brightness Min" switch before changing the value of this
  - platform: tuya
    number_datapoint: 3
    name: "Brightness Min"
    id: id_number_brightness_min
    min_value: 0
    max_value: 500
    step: 1
    entity_category: config
    web_server:
      sorting_weight: 12
  #- platform: tuya
  #  number_datapoint: 6
  #  name: "Countdown 1"
  #  unit_of_measurement: S
  #  min_value: 0
  #  max_value: 86399
  #  step: 1
  #- platform: tuya
  #  number_datapoint: 111
  #  name: "Countdown Total"
  #  unit_of_measurement: S
  #  min_value: 0
  #  max_value: 86399
  #  step: 1

select:
  - platform: tuya
    enum_datapoint: 103
    name: "Fade On Speed"
    id: id_select_fade_on_speed
    optimistic: true
    options:
      0: "Immediate"
      1: "Fast"   # 1s
      2: "Medium" # 5s
      3: "Slow"   # 15s
    entity_category: config
    web_server:
      sorting_weight: 20
  - platform: tuya
    enum_datapoint: 104
    name: "Fade Off Speed"
    id: id_select_fade_off_speed
    optimistic: true
    options:
      0: "Immediate"
      1: "Fast"   # 1s
      2: "Medium" # 5s
      3: "Slow"   # 15s
    entity_category: config
    web_server:
      sorting_weight: 21
  - platform: tuya
    enum_datapoint: 4
    name: "Bulb Type"
    id: id_select_bulb_type
    optimistic: true
    options:
      0: "Cfl"
      1: "Incandescent"
      2: "Halogen"
      3: "Led"
    entity_category: config
    web_server:
      sorting_weight: 30

light:
  - platform: tuya
    name: "Dimmer"
    id: dimmer
    dimmer_datapoint: 2
    min_value: 10
    max_value: 1000
    switch_datapoint: 1
    web_server:
      sorting_weight: -1
    on_turn_on:
      then:
        if:
          condition:
            and:
              - lambda: |-
                  return id(indicator_on_with_dimmer_state) == true;
              - lambda: |-
                  return id(change_indicator_brightness_with_dimmer_state) == true;
          then:
            - number.set:
                id: indicator_brightness
                value: !lambda |-
                  return id(indicator_brightness_when_on).state;
    on_turn_off:
      then:
        if:
          condition:
            and:
              - lambda: |-
                  return id(indicator_on_with_dimmer_state) == true;
              - lambda: |-
                  return id(change_indicator_brightness_with_dimmer_state) == true;
          then:
            - delay: 500ms
            - number.set:
                id: indicator_brightness
                value: !lambda |-
                  return id(indicator_brightness_when_off).state;

interval:
  # Normally indicator turns off when dimmer switch turns on. This forces the indicator to stay on.
  - interval: 4s
    startup_delay: 4s
    then:
      - if:
          condition:
            and:
              - lambda: |-
                  return id(indicator_on_with_dimmer_state) == true;
          then:
            - lambda: |-
                id(id_tuya_device).force_set_integer_datapoint_value(101, id(indicator_brightness).state);
  # Workaround for rare occasions whenre indicator brightness is not being taken in by TuyaMCU
  - interval: 1min
    startup_delay: 1min
    then:
      - if:
          condition:
            and:
              - lambda: |-
                  return id(indicator_on_with_dimmer_state) == false;
              - light.is_off: dimmer
          then:
            - lambda: |-
                id(id_tuya_device).force_set_integer_datapoint_value(101, id(indicator_brightness).state);